version: "3.9"
services:
  web:
    image: nginx:latest
    working_dir: /var/www
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:7-fpm
    working_dir: /var/www
    volumes:
      - ./:/var/www